### ISSUE TITLE
Missing Box Shadow for Better Visual Depth

### ISSUE THREAD

**Issue by jayco01** [Shahd-Abdalghny/Testimonials#1]
I noticed that the cards don't have a **box shadow**, which makes the transition between the cards and the background feel a bit harsh. Adding a subtle shadow can help create better visual separation and depth, making the design look more polished.

---

### **Suggested Solution**
To improve this, you could add a `box-shadow` to `.container .box` like this:

```css
.container .box {
    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
}
```

This will give the cards a soft shadow, making the design feel more layered and modern. You can tweak the shadow values to match the aesthetic you're aiming for.
